services:
  ww:
    hostname: ww
    build: ./
    env_file:
      - path: .env
    ports:
      - "5007:5007"
    volumes:
      - ./:/usr/src/app/
    command: sleep infinity  # Keep container running
