services:
  ww:
    hostname: ww
    build: ./
    env_file:
      - path: app/.env
    ports:
      - "127.0.0.1:5007:5007"
    volumes:
      - ./:/usr/src/app/
    command: sleep infinity  # Keep container running
