services:
  ww:
    hostname: ww
    build: 
      context: .
      dockerfile: Dockerfile
    env_file:
      - path: .env
    ports:
      - "127.0.0.1:5007:5007"
      - "8080:8080"
    volumes:
      - .:/usr/src/app/
    networks:
      - app-network
    # command: sleep infinity  # Keep container running

  # Note: this is for local development only
  db:
    #This adds pgvector to the Postgres image (https://github.com/pgvector/pgvector?tab=readme-ov-file#docker)
    image: pgvector/pgvector:pg17
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: postgres
    ports:
      - "5433:5432"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
