# fly.toml app configuration file generated for wraeclast-whisperer-wispy-brook-8021 on 2025-01-03T20:41:10-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'wraeclast-whisperer-wispy-brook-8021'
primary_region = 'dfw'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[env]
  PORT = "8080"
  HOST = "0.0.0.0"

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
